services:
  web:
    build:
      dockerfile: ./Dockerfile.dev
    environment:
      JWT_SECRET: 'jwt-secret'
      JDBC_DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/ktor_notes
      JDBC_DATABASE_USER: ${POSTGRES_USER:-postgres}
    ports:
      - "81:8081"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ktor_notes
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "54322:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ktor_notes -U $${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5