services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ktor_notes
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54333:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s