FROM gradle:7-jdk11 as build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle buildFatJar --no-daemon

FROM openjdk:11 as build
EXPOSE 8081:8081
RUN mkdir /app
COPY ./build/libs/*.jar /app/ktor-simple-rest-api.jar
ENTRYPOINT ["java","-jar","/app/ktor-simple-rest-api.jar"]