name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_PASSWORD: ktor
          POSTGRES_DB: ktor
          POSTGRES_USER: ktor
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Migrations
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://postgres:5432/ktor
          user: ktor
          password: ktor
          locations: filesystem:./src/main/resources/db/migration/

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Gradle compile and test
        run: ./gradlew clean test
        env:
          JWT_SECRET: 'jwt-secret'
          JDBC_DATABASE_PASSWORD: ktor
          JDBC_DATABASE_URL: jdbc:postgresql://127.0.0.1:5432/ktor
          JDBC_DATABASE_USER: ktor

      - name: Archive test results report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tests-report
          path: /home/runner/work/ktor-simple-rest-api/ktor-simple-rest-api/build/reports/tests

