name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  POSTGRES_PASSWORD: ktor
  POSTGRES_DB: ktor
  POSTGRES_USER: ktor
  JWT_SECRET: 'jwt-secret'
  JDBC_DATABASE_PASSWORD: ktor
  JDBC_DATABASE_URL: jdbc:postgresql://0.0.0.0:5432/ktor
  JDBC_DATABASE_USER: ktor

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB
          POSTGRES_USER: $POSTGRES_USER
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Migrations
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: $JDBC_DATABASE_URL
          user: $JDBC_DATABASE_USER
          password: $JDBC_DATABASE_PASSWORD

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Gradle compile and test
        run: ./gradlew clean test
